name: Automerge

on:
  pull_request:
    types:
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  tags:
      - v*
  status: {}

jobs:
  auto-merge:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: 'pascalgn/automerge-action@v0.15.5'
        env:
          GITHUB_TOKEN: '${{ secrets.RELEASE_TOKEN }}'
          MERGE_LABELS: 'autorelease'
          MERGE_FILTER_AUTHOR: 'LIjiAngChen8' 
