name: Code Check
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: yarn install

      - name: mock time
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Asia/Shanghai'
          timezoneMacos: 'Asia/Shanghai'
          timezoneWindows: 'China Standard Time'

      - name: run test
        run: yarn test
