name: github-npm

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          cache: 'yarn'
          
     - name: Cache
        if: ${{ steps.release.outputs.release_created }}
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{runner.OS}}-gitnpm-${{hashFiles('**/yarn.lock')}}
          
      - name: Yarn
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn
        
      - name: Build
        run: yarn build 
        
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITNPMTOKEN}}
